Add support for pang13
pop-os/system76-firmware pull request #118
Opened 2023-08-31 22:22 UTC by leviport

2023-09-01 00:31 UTC, jackpot51 approved these changes

2023-09-01 00:33 UTC, jackpot51 requested changes
There are changes to read pang12 EC version that need to be done on pang13

2023-09-01 00:48 UTC, jackpot51 approved these changes

2023-09-06 16:30 UTC, jacobktm approved these changes

2023-09-06 16:36 UTC, merged

2023-09-06 23:03 UTC, jackpot51 commented
This will need a new tag

2023-09-06 23:15 UTC, leviport commented
Tagged: https://github.com/pop-os/system76-firmware/releases/tag/1.0.53