Add meer6
pop-os/system76-firmware pull request #61
Opened 2021-05-25 16:51 UTC by jacobgkau

Adds meer6 to the list of models supporting over-the-air firmware updates.

2021-05-25 17:10 UTC, leviport submitted a review, later dismissed

2021-05-25 21:34 UTC, jackpot51 requested changes
Please update debian/changelog

2021-05-27 16:13 UTC, jackpot51 requested changes
Run `cargo update` so Cargo.lock is up to date

2021-05-27 16:17 UTC, jackpot51 approved these changes

2021-05-27 16:18 UTC, merged