Cleanup
pop-os/system76-firmware pull request #92
Opened 2022-07-31 18:37 UTC by crawfxrd

2022-07-31 18:38 UTC, crawfxrd commented on rust-toolchain
> +1.62.1
Do we have some kind of minimum version? Our toolchain files seem to be all over the place.

2022-07-31 18:40 UTC, crawfxrd commented on Cargo.toml
>  tar = "=0.4.35"
Need to check if tar can be updated (ref: #71).

2022-09-14 23:31 UTC, XV-02 submitted a review, later dismissed
On both open and closed firmware systems, this successfully flashed the latest released firmware. It built correctly (though did reveal a needed tweak to the `README` instructions, namely that those looking to build should run `apt build-dep system76-firmware` first) and didn't present any regressions while testing those features. It was tested across three laptops (Pang11, Lemp9, Oryp9) and a desktop (Mira-B1)

2022-09-15 17:46 UTC, 13r0ck approved these changes

2022-11-10 22:33 UTC, jackpot51 approved these changes

2023-01-18 18:23 UTC, jackpot51 submitted a review, later dismissed

2023-01-19 21:08 UTC, XV-02 submitted a review, later dismissed
Everything is looking good. Tested on Galp6, Oryp10, and Galp5. Works without any issues. Approved.

2023-01-20 17:26 UTC, crawfxrd commented
It looks  like https://github.com/alexcrichton/tar-rs/commit/d90a02f582c03dfa0fd11c78d608d0974625ae5d is what broke it. It's failing on the `res/` directory in the archive, which it's suppose to create while extracting.

2023-01-20 21:48 UTC, crawfxrd commented on Cargo.toml
>  tar = "=0.4.35"
Fixed the problem with newer versions of tar.

2023-01-20 21:52 UTC, crawfxrd commented
- Archive timestamp issue fixed in system76/firmware/pull/476
- Issue with newer versions of tar fixed
- Replaced deprecated tempdir with tempfile

2023-01-23 20:29 UTC, jackpot51 submitted a review, later dismissed

2023-02-07 01:12 UTC, leviport requested changes
This appears to break the firmware application in Ubuntu Focal. I think we probably just need to make a `master_focal` so the old version can remain on the old release.

2023-02-07 15:19 UTC, crawfxrd commented
> This appears to break the firmware application in Ubuntu Focal.

Does it fail to start or does it not work in some way?

2023-02-07 15:37 UTC, leviport commented
The window appears, but the window is blank and I can't interact with it, then the "force quit" prompt appears.

2023-03-02 18:19 UTC, crawfxrd commented
I'm going to do the tar changes separately, since I think that is what is breaking it.

2023-03-02 23:37 UTC, leviport commented
Yep, looks like that fixed it on Ubuntu Focal. I'm going to do some quick tests on Pop, but I'll probably be approving this very soon.

2023-03-03 00:07 UTC, leviport submitted a review, later dismissed

2023-10-03 19:39 UTC, leviport approved these changes
Seems good on Pop and Ubuntu

2023-10-03 20:00 UTC, jackpot51 approved these changes

2023-10-03 20:00 UTC, merged